### ISSUE TITLE
[fixed] Stack Exception in Forest Outskirts

### ISSUE THREAD

**Issue by Norren** [AftianSpheres/malta#1]
Received Stack Exception error on the WebGL build, Forest Outskirts Battle 3/3.

Had hired second Human, upgraded him once, and retrained him to Mystic.  Game appeared to crash when the Mystic was killed in battle, but something else may have happened instead.

**Comment by AftianSpheres** [comment]
Not actually a stack overflow, it's just that the dev webGL builds that actually handle exceptions nicely are also way too bloated for, uh, actually hosting as web apps. Internally: the problem is something really dumb I did in Battler.ReadyAttack. I was setting list indices directly immediately after clearing the list. Originally the subtarget acquisition code used an array, before it became clear that with the amount of housekeeping I was doing I may as well just suck it up and use a List<Battler> instead. So you had this:

`Battler[] subtargets = new Battler[n] // I want to believe this compiles to four pointers but it probably doesn't`

`for (int i = 0; i < something; i++) subtargets[i] = getRandomWhatever()`

turn into this:

`subtargets.Clear() // subtargets now contains no objects`

`for (int i = 0; i < something; i++) subtargets[i] = getRandomWhatever() // you know the not-a-thing at index i? this is the something that nothing is`

Unsurprisingly, this crashed. My testing practices aren't great, if I'm honest.

It didn't crash because the Mystic died; it crashed because the enemy Sage has an attack that gets subtargets and it immediately set about trying to stick its acquired subtarget in an invalid index in the 0-count list.

Fixed it now. Just needed to actually _use the List object's functionality_ and make an Add() call instead of poking shit straight into it with indexers. Commit will be up after the new webGL build finishes. Sorry for the inconvenience!
